# Generated by Django 5.1.7 on 2025-03-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [


    ]
