# Generated by Django 5.1.5 on 2025-04-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssignedTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=50)),
                ('material_used', models.FloatField(blank=True, db_column='Material_Used', null=True)),
                ('processing_time', models.FloatField(blank=True, db_column='Processing_Time', null=True)),
                ('energy_consumption', models.FloatField(blank=True, db_column='Energy_Consumption', null=True)),
                ('machine_availability', models.FloatField(blank=True, db_column='Machine_Availability', null=True)),
                ('machine_id', models.CharField(blank=True, db_column='Machine_ID', max_length=50, null=True)),
                ('time_budget', models.FloatField(blank=True, db_column='Time_Budget', null=True)),
                ('time_risk', models.FloatField(blank=True, db_column='Time_Risk', null=True)),
                ('exceeds_deadline', models.IntegerField(blank=True, db_column='Exceeds_Deadline', null=True)),
                ('priority_label', models.CharField(blank=True, db_column='Priority_Label', max_length=20, null=True)),
                ('scheduled_start', models.DateTimeField(blank=True, db_column='Scheduled_Start', null=True)),
                ('deadline', models.DateTimeField(blank=True, db_column='Deadline', null=True)),
                ('priority_score', models.FloatField(db_column='Priority_Score')),
            ],
            options={
                'db_table': 'assigned_tasks',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_used', models.FloatField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('energy_consumption', models.FloatField(blank=True, null=True)),
                ('machine_availability', models.FloatField(blank=True, null=True)),
                ('machine_id', models.CharField(blank=True, max_length=50, null=True)),
                ('time_budget', models.FloatField(blank=True, null=True)),
                ('time_risk', models.FloatField(blank=True, null=True)),
                ('exceeds_deadline', models.IntegerField(blank=True, null=True)),
                ('priority_label', models.CharField(blank=True, max_length=20, null=True)),
                ('scheduled_start', models.DateTimeField(blank=True, db_column='Scheduled_Start', null=True)),
                ('deadline', models.DateTimeField(blank=True, db_column='Deadline', null=True)),
            ],
            options={
                'db_table': 'historical_tasks',
            },
        ),
        migrations.CreateModel(
            name='UnassignedTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=50)),
                ('material_used', models.FloatField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('energy_consumption', models.FloatField(blank=True, null=True)),
                ('machine_availability', models.FloatField(blank=True, null=True)),
                ('machine_id', models.CharField(blank=True, max_length=50, null=True)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unassigned_tasks',
            },
        ),
    ]
