# Generated by Django 5.1.7 on 2025-04-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedtasks',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='historicaltasks',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='unassignedtasks',
            options={'managed': True},
        ),
    ]
