# Generated by Django 5.1.7 on 2025-04-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedtasks',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historicaltasks',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unassignedtasks',
            options={},
        ),
    ]
